export type Request = {
  id: number;
  requestDate: Date;
  requestTitle: string;
  description: string;
  requestedBy: string;
  department: string;
  explainImpact: string;
  hasStakeholderConferred: boolean;
  proposedImpDate: Date;
  boardDate: Date;
  approvalDate: Date;
  denialDate: Date;
  policies: string[];
  relatedProjects: string[];
  isNew: boolean;
  isActive: boolean;
  sendToBoard: boolean;
  approvalStatus: string;
  priority: string;
  requestType: string;
  requestStatus: string;
};
